### ISSUE TITLE
CPU mode is broken

### ISSUE THREAD

**Issue by ostrokach** [barbagroup/pygbe#68]
I'm trying to get PyGBe to run in CPU mode, but this seems untested and broken?

Running `pygbe examples/lys/`, I get:

```python-traceback
        Date: 2018/5/24
        Time: 15:14:27
        PyGBe version: 0.3.1+13.gcd21bfd.dirty
Config file: /username/packages/pygbe/examples/lys/lys.config
Parameter file: /username/packages/pygbe/examples/lys/lys.param
Geometry folder: /username/packages/pygbe/examples/lys/geometry
Running in: /username/packages/pygbe/examples/lys
which: no nvcc in (/home/username/anaconda3/envs/pygbe/bin:/home/username/anaconda3/bin:/home/username/.cargo/bin:/home/username/bin/rosetta_bin_linux_2017.26.59567_bundle/main/source/bin:/usr/local/cuda-9.0/bin:/home/username/bin:/home/username/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/dell/srvadmin/bin)
Could not find `nvcc` on your PATH.  Is cuda installed?  PyGBe will continue to run but will run significantly slower.  For optimal performance, add `nvcc` to your PATH

Reading surface 0 from file geometry/Lys1_stern
Time load mesh: 0.47818589210510254
Removed areas=0: 0

Reading surface 1 from file geometry/Lys1
Time load mesh: 0.38768768310546875
Removed areas=0: 0

Reading surface 2 from file geometry/Lys1_1
Time load mesh: 0.0027697086334228516
Removed areas=0: 0

Reading surface 3 from file geometry/Lys1_2
Time load mesh: 0.008854866027832031
Removed areas=0: 0

Reading surface 4 from file geometry/Lys1_3
Time load mesh: 0.0024976730346679688
Removed areas=0: 0

Total elements : 30170
Total equations: 60340
----------------------------

5 surfaces:

Surface 0:
        15324 elements
        Surface type         : stern_layer
        Cells                : 139
        Twigs                : 115
        Levels               : 4
        C0 size              : 29.958532459480036
        C0 box center        : -0.48149856434351346, 20.911416731923783, 19.102714391368657
        Twig cell size       : 3.7448165574350045
        Rbox/theta           : 7.489633114870009
        Analytic distance    : 1.0604318114186524
        Elem. per Ang^2      : 2.454591046986522
        Max, min, avg elem.  : 1.693938795185128, 2.6981475126454322e-05, 0.4073998400783261
        Total area           : 6242.995149360268
Surface 1:
        14398 elements
        Surface type         : dielectric_interface
        Cells                : 119
        Twigs                : 99
        Levels               : 4
        C0 size              : 27.889694408153325
        C0 box center        : -0.7368682455896652, 20.940657799694403, 19.297709728202992
        Twig cell size       : 3.4862118010191656
        Rbox/theta           : 6.972423602038331
        Analytic distance    : 0.9835300618160833
        Elem. per Ang^2      : 2.717396662760249
        Max, min, avg elem.  : 1.8742335126168892, 4.999999999990016e-07, 0.367999274343787
        Total area           : 5298.453552001845
Surface 2:
        66 elements
        Surface type         : internal_cavity
        Cells                : 1
        Twigs                : 1
        Levels               : 1
        C0 size              : 1.4465839199720398
        C0 box center        : -3.6661363636363635, 16.895954545454547, 16.303005050505053
        Twig cell size       : 1.4465839199720398
        Rbox/theta           : 2.8931678399440797
        Analytic distance    : 0.8804616208379404
        Elem. per Ang^2      : 2.9532814320236795
        Max, min, avg elem.  : 0.8930060331438131, 0.0010528354572296131, 0.3386064020707871
        Total area           : 22.34802253667195
Surface 3:
        312 elements
        Surface type         : internal_cavity
        Cells                : 1
        Twigs                : 1
        Levels               : 1
        C0 size              : 3.6946448572969266
        C0 box center        : -0.2893023504273504, 11.941264957264957, 17.98145192307692
        Twig cell size       : 3.6946448572969266
        Rbox/theta           : 7.389289714593853
        Analytic distance    : 0.8216105509874814
        Elem. per Ang^2      : 3.7866866083455575
        Max, min, avg elem.  : 0.8872255697773541, 0.0031433756536565108, 0.2640831163043911
        Total area           : 82.39393228697001
Surface 4:
        70 elements
        Surface type         : internal_cavity
        Cells                : 1
        Twigs                : 1
        Levels               : 1
        C0 size              : 1.492959249944708
        C0 box center        : 1.6802000000000001, 16.586542857142856, 20.228666666666665
        Twig cell size       : 1.492959249944708
        Rbox/theta           : 2.985918499889416
        Analytic distance    : 0.9135549729565667
        Elem. per Ang^2      : 2.927740042748632
        Max, min, avg elem.  : 0.9799117031713879, 0.002391581537393256, 0.3415603794731639
        Total area           : 23.909226563121475
------------------------------

6 regions:

Region 0:
        Laplace or Yukawa: 2
        kappa            : 0.125
        dielectric const : 80.0
        Number of charges: 0
        Parent surface   : []
        Child surfaces   : [0]
Region 1:
        Laplace or Yukawa: 1
        kappa            : 1e-12
        dielectric const : 80.0
        Number of charges: 0
        Parent surface   : [0]
        Child surfaces   : [1]
Region 2:
        Laplace or Yukawa: 1
        kappa            : 1e-12
        dielectric const : 4.0
        Number of charges: 1323
        Parent surface   : [1]
        Child surfaces   : [2, 3, 4]
Region 3:
        Laplace or Yukawa: 1
        kappa            : 1e-12
        dielectric const : 80.0
        Number of charges: 0
        Parent surface   : [2]
        Child surfaces   : []
Region 4:
        Laplace or Yukawa: 1
        kappa            : 1e-12
        dielectric const : 80.0
        Number of charges: 0
        Parent surface   : [3]
        Child surfaces   : []
Region 5:
        Laplace or Yukawa: 1
        kappa            : 1e-12
        dielectric const : 80.0
        Number of charges: 0
        Parent surface   : [4]
        Child surfaces   : []
------------------------------

Parameters:
        Data type               : <class 'numpy.float64'>
        Use GPU                 : 0
        P                       : 2
        threshold               : 0.80
        theta                   : 0.50
        NCRIT                   : 500
        CUDA block size         : 128
        Gauss points per element: 1
        Gauss points near singlr: 19
        1D Gauss points per side: 5
        GMRES tolerance         : 0.0001
        GMRES max iterations    : 1000
        GMRES restart iteration : 200
----------------------------

Generate interaction list
Transfer data to GPU
Generate RHS
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/pygbe/bin/pygbe", line 11, in <module>
    load_entry_point('PyGBe==0.3.1+13.gcd21bfd.dirty', 'console_scripts', 'pygbe')()
  File "/home/username/anaconda3/envs/pygbe/lib/python3.6/site-packages/PyGBe-0.3.1+13.gcd21bfd.dirty-py3.6-linux-x86_64.egg/pygbe/main.py", line 348, in main
    F = generateRHS(field_array, surf_array, param, kernel, timing, ind0)
  File "/home/username/anaconda3/envs/pygbe/lib/python3.6/site-packages/PyGBe-0.3.1+13.gcd21bfd.dirty-py3.6-linux-x86_64.egg/pygbe/matrixfree.py", line 584, in generateRHS
    LorY = field_array[j].LorY
NameError: name 'j' is not defined
```

This is not surprising, since `j` is not defined at this point (see [matrixfree.py#L584](https://github.com/barbagroup/pygbe/blob/79ded4f17154ef5c00e79d978eee90897e6260e4/pygbe/matrixfree.py#L584)).

Is calculating electrostatics in CPU mode no longer supported (and not tested)?

Thanks!

**Comment by ostrokach** [comment]
Great, thank you!
